### ISSUE TITLE
Using a specific version of carto

### ISSUE THREAD

**Issue by pnorman** [mapbox/tilemill#2472]
Different carto versions between production and development recently caused problems (gravitystorm/openstreetmap-carto#1294).

How would I install/run Tilemill to make use of a specific version of carto?

Cross-ref kosmtik/kosmtik#43

**Comment by springmeyer** [comment]
> How would I install/run Tilemill to make use of a specific version of carto?

The carto version used is controlled by the `package.json` file, which npm uses to install dependencies. 

See 
https://github.com/mapbox/tilemill/blob/c6090b85fe83431063ece0942b56734682578b17/package.json#L45 which says that at least carto `0.14.1` is required for this version of TileMill.

If you wanted to run a different version of carto then you would change that value and then re-install. However, that is not currently supported: it would break TileMill in this case because current master TileMill depends on API changes in how Carto gets initialized (https://github.com/mapbox/tilemill/commit/6c8a4f33b32f071ce0035f60f097e0f3a5c067f7).

So, there are two options:

  1) Ensure you are using Carto 0.14.1, or;
  2) Make changes to your TileMill versions to dynamically adapt to various Carto versions so a more flexible range of Carto versions could be supported.

Does that help?

**Comment by pnorman** [comment]
> Does that help?

Somewhat - thanks. So for an install procedure it would be get the source, force carto to 0.14.1 in package.json, and build as normal?

I suppose what's really needed more is the same version of CartoCSS, but because carto is basically the only processor of CartoCSS it's difficult to separate the two.

**Comment by springmeyer** [comment]
> So for an install procedure it would be get the source, force carto to 0.14.1 in package.json, and build as normal?

Well yes, but to be clear: tilemill source/master already uses carto 0.14.1 as per package.json.

So I think what you want to to so is ensure you are installing carto 0.14.1 if you install carto outside of TileMill, so doing `npm install carto@0.14.1`

**Comment by pnorman** [comment]
> Well yes, but to be clear: tilemill source/master already uses carto 0.14.1 as per package.json

It uses it *now* - but I'm thinking to the future when it presumably won't.

**Comment by tmcw** [comment]
If you need a specific version of Carto, you'll need to use the TileMill version that includes it. Versioning is such that the two cannot be arbitrarily mixed-and-matched.
